### ISSUE TITLE
Adhoc for verify proxy action

### ISSUE THREAD

**Issue by kumarabd** [meshery/meshery-linkerd#116]
Add option for running verify proxy planes installed.

**Comment by leecalcote** [comment]
# Check that the Linkerd control plane is up and running
`linkerd check`

# Check that the Linkerd control plane can be installed in the "test" namespace
`linkerd check --pre --linkerd-namespace test`

# Check that "linkerd install config" succeeded
`linkerd check config`

# Check that the Linkerd data plane proxies in the "app" namespace are up and running
`linkerd check --proxy --namespace app`
