### ISSUE TITLE
[README] Update README Community Section

### ISSUE THREAD

**Issue by Anita-ihuman** [meshery/meshery-linkerd#189]
**Description**
The Community section in the README says "Access the Community Drive". There is a new procedure of having this automated based on the individual filling in a [community member form](https://layer5.io/newcomer)

**Expected Behavior**
Update "Access Community Drive" to "To Access Community Drive, fill Community Member Form"

**Screenshots**
![img](https://user-images.githubusercontent.com/62384659/117368468-7cbfe400-aebb-11eb-92c2-0033fd74bcfc.png)
--

**Resources**
Refer to the [Contributing guide](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#contributing)

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

**Comment by XeroHero** [comment]
Hi @Anita-ihuman . 
I'd like to give this one a try, would that be okay for you? Could you kindly assign it to myself?
Thank you very much. Regards.
Xerohero

**Comment by leecalcote** [comment]
Thank you for volunteering, @XeroHero! 👍

**Comment by Anita-ihuman** [comment]
@XeroHero, How is this coming up?
