### ISSUE TITLE
[README] Need to fix Slack badge

### ISSUE THREAD

**Issue by amino19** [meshery/meshery-linkerd#201]
**Description**

<a href="https://github.com/layer5io/meshery-linkerd/blob/master/README.md">README.md</a> is the first file one should read when starting a new project. For attractive look, we added some badges also.
But, there's a Slack badge failing, need to fix that. 
 
### Example Screenshot

**Current Behavior**

![image](https://user-images.githubusercontent.com/75872316/122434243-8d807100-cfb4-11eb-9d27-2a556131c631.png)

**Desired Behavior**
![image](https://user-images.githubusercontent.com/75872316/122434111-6fb30c00-cfb4-11eb-802c-da8745c47585.png)

**Environment:**
 - OS: any [e.g. Ubuntu]
 - Browser: any [e.g. Chrome, Safari]
 - Version: any [e.g. 22]
 - Device: any [e.g. laptop, iPhone 8]

**Comment by Aisuko** [comment]
related to https://github.com/meshery/meshery-linkerd/issues/202#issuecomment-870170746

**Comment by aaroosh-07** [comment]
can i take up this issue?

**Comment by amino19** [comment]
@aaroosh-07 : Yes, do you mind to fix #202 as well! :slightly_smiling_face:

**Comment by aaroosh-07** [comment]
okay I will also take up issue #202

**Comment by aaroosh-07** [comment]
@amino19 I have made pull request to solve this issue and #202
