### ISSUE TITLE
[README] Need to add `Community Forum`

### ISSUE THREAD

**Issue by amino19** [meshery/meshery-linkerd#202]
**Description**

<a href="https://github.com/layer5io/meshery-linkerd/blob/master/README.md">README.md</a> is the first file one should read when starting a new project. Our community launched `Discussion forum` for help seekers; needs to publish it officially on README.md for convenience.

### Screenshots

**Current behaviour:**
![image](https://user-images.githubusercontent.com/75872316/123441080-16209200-d5f1-11eb-8cac-0f82770161e6.png)

**Desired behaviour:**
![image](https://user-images.githubusercontent.com/75872316/123440623-9d213a80-d5f0-11eb-8ffd-87ba14c0159b.png)

**Note:**
Need to add only last line for `Community Forum`

**Environment:**
 - OS: any [e.g. Ubuntu]
 - Browser: any [e.g. Chrome, Safari]
 - Version: any [e.g. 22]
 - Device: any [e.g. laptop, iPhone 8]

---
**Reference:**
- Take reference to this <a href="https://github.com/layer5io/layer5/pull/1949">pull request</a>

**Comment by Aisuko** [comment]
hi @amino19 , thank for mention this. I saw there both issue type `README` all comes from you, so, welcome to do PR for this.

**Comment by gravishpurohit** [comment]
Hey , @amino19 can i take this?

**Comment by amino19** [comment]
@gravishpurohit : Thanks for your attention over here, I think this issue got fixed, make sure to check more <a href="https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22good+first+issue%22"> good-first-issue</a> to get started...
Else you can join our <a href="https://slack.layer5.io">slack</a> for more info. :slightly_smiling_face:
