### ISSUE TITLE
[CI] Patterns: Generate JSON Schema and Definitions for LINKERD components

### ISSUE THREAD

**Issue by sayantan1413** [meshery/meshery-linkerd#211]
**Enhancement Description**

To generate the workflow of getting the manifest from the LINKERD using the [kubeopenapi-jsonschema](https://github.com/layer5io/kubeopenapi-jsonschema) to read and generate json schemas from those manifests and then also generating workload definitions from those schemas.

A sample workflow is [here](https://github.com/DelusionalOptimist/meshery-istio/blob/gen-oam/.github/workflows/update-oam-defs.yml)

---

**Comment by leecalcote** [comment]
@sayantan1413, are you working on this one (taking assignment)?
