### ISSUE TITLE
[CI] add error codes utility runner workflow

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshery-linkerd#213]
#### Current Behavior

Error codes and their reference is not being updated.
#### Desired Behavior

Add the error codes updater workflow to update error codes and publish error codes reference

#### Implementation

1. Create the error codes updater workflow for the repo. Modify it a bit according to the repository you're working on.
Sample: https://github.com/layer5io/meshkit/blob/master/.github/workflows/error-codes-updater.yaml
2. Delete `errorutil_analyze_errors.json` `errorutil_analyze_summary.json` `errorutil_errors_export.json`
3. Add the three files from previous step to `.gitignore`
Sample: https://github.com/layer5io/meshkit/blob/5bc1f9c13e60c7674d8b8c1d8ea434cbb2ce08fd/.gitignore#L21-L23
4. Also remove them from cache using 
`git rm --cached errorutil_analyze_errors.json errorutil_analyze_summary.json errorutil_errors_export.json`
5. Move `component_info.json` to a `helpers` directory.
6. Update command for running utility in Makefile to :
```make
	error:
	go run github.com/layer5io/meshkit/cmd/errorutil -d . analyze -i ./helpers -o ./helpers
```

**Comment by metonymic-smokey** [comment]
@DelusionalOptimist https://github.com/layer5io/meshkit/blob/master/.github/workflows/error-ref-publisher.yaml - this link mentioned above returns a 404 for me

**Comment by leecalcote** [comment]
Having a look-see at the changes included in the PRs above will be insightful.

**Comment by metonymic-smokey** [comment]
Yep @leecalcote , I understood the instructions from those.
Just wanted to notify @DelusionalOptimist to change it in the issue description.

**Comment by DelusionalOptimist** [comment]
> @DelusionalOptimist https://github.com/layer5io/meshkit/blob/master/.github/workflows/error-ref-publisher.yaml - this link mentioned above returns a 404 for me

Yeah my bad. Thanks for bringing this up @metonymic-smokey. I've updated the link 👍
