### ISSUE TITLE
Linkerd fails to install

### ISSUE THREAD

**Issue by DelusionalOptimist** [meshery/meshery-linkerd#215]
**Description**
Unable to install linkerd using the adapter.

**Screenshot**
Logs from the linkerd adapter
```
INFO[2021-07-24T19:18:46Z] Creating instance                             app=linkerd-adaptor
INFO[2021-07-24T19:18:46Z] Applying operation linkerd                    app=linkerd-adaptor
INFO[2021-07-24T19:18:46Z] Requested install of version:                 app=linkerd-adaptor
INFO[2021-07-24T19:18:46Z] Requested action is delete: false             app=linkerd-adaptor
INFO[2021-07-24T19:18:46Z] Requested action is in namespace: default     app=linkerd-adaptor
INFO[2021-07-24T19:18:46Z] Looking for linkerd in the path...            app=linkerd-adaptor
INFO[2021-07-24T19:18:46Z] Looking for linkerd in/home/azureuser/.meshery/bin...  app=linkerd-adaptor
INFO[2021-07-24T19:18:46Z] linkerd not found in the path, downloading...  app=linkerd-adaptor
ERRO[2021-07-24T19:18:46Z]                                               app=linkerd-adaptor code=1003 probable-cause= severity=2 short-description="Error with Linkerd operation: ." suggested-remediation=
ERRO[2021-07-24T19:18:46Z]                                               app=linkerd-adaptor code=1003 probable-cause= severity=2 short-description="Error with Linkerd operation: ." suggested-remediation=

```

**Enviroment:**
 - OS: Ubuntu 20.04
 - Browser: Any
 - Version: [e.g. 22]
 - Device: [e.g. laptop]

---
**To Reproduce**
1. Install meshery and meshery-linkerd adapter.
2. Go to linkerd page in the UI.
3. Install linkerd.

**Additional Context**
My hunch and some debugging says that while installing it tries to fetch linkerd's cli using this bad URL
`https://github.com/linkerd/linkerd2/releases/download//linkerd2-cli--linux-amd64`
instead this url should look something like
`https://github.com/linkerd/linkerd2/releases/download/edge-21.7.4/linkerd2-cli-edge-21.7.4-linux-amd64`

**Comment by leecalcote** [comment]
@Aisuko, I wonder if you might have a peek...

**Comment by Aisuko** [comment]
No problem, sir.

**Comment by utkarsh-pro** [comment]
@Aisuko let's consider using linkerd's helm chart for installation as chart based installation should be more reliable. Meshkit already supports helm chart based installations (Traefik Mesh uses this I believe). 

Opinions @leecalcote @DelusionalOptimist?

**Comment by Aisuko** [comment]
We will close this issue after we got confirmation from the PR was linked above.

**Comment by Aisuko** [comment]
There may be other issues you are interested in @Micost

**Comment by Micost** [comment]
> There may be other issues you are interested in @Micost

Thank you for the understanding,  I was out of other things.
