### ISSUE TITLE
Support Linkerd Extensions

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-linkerd#245]
**Enhancement Description**
Add component support for Linkerd Extensions - https://linkerd.io/2.11/reference/extension-list/

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by s1ntaxe770r** [comment]
@leecalcote could I work on this? I'd need a bit of help though

**Comment by leecalcote** [comment]
@s1ntaxe770r, yes, although considering that this a good deal different than where you've focused in the past, let's set you up for success by having as a reviewer the PR that comes through on this issue. Will that work? // @Revolyssup

**Comment by s1ntaxe770r** [comment]
ah yes that works
