### ISSUE TITLE
[Docs]The updation of shields is needed in README.md

### ISSUE THREAD

**Issue by Swapnil-Bhabal** [meshery/meshery-linkerd#269]
**Current State:**
Small updation of shields in README.md

![image](https://user-images.githubusercontent.com/61308713/146510760-3b91a7c4-713a-40a3-9111-81076992c778.png)

**Desired State:**
This is how it should look like:

![image](https://user-images.githubusercontent.com/61308713/146510848-68194696-4ee9-4a33-9f0c-68759eb05de7.png)

updation should be done in this README.md by keeping the shield style uniform to following meshery-istio's README.md :
https://github.com/meshery/meshery-istio/blob/721b78783182e65145cefde64d905dab3ca20ba1/README.md?plain=1#L13

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by sayantan1413** [comment]
So basically you will be adding the discourse shield right ?

**Comment by sayantan1413** [comment]
Assigned!!

**Comment by Swapnil-Bhabal** [comment]
Yes @sayantan1413, this updation was proposed by lee calcote sir, he wanted the shield section to be same as the shield of meshery-istio in every repository.

Being a new comer i took up this task and i am raising issues from every repository.

Updations of few repositories will be done by me, and the remaining links i am planning to post in community new comers channel so it serve as first contribution to every new comers as well.

**Comment by Swapnil-Bhabal** [comment]
#270 
Thats my PR on this issue @sayantan1413 , i have made the changes 
Kindly review my PR, Thank you.

**Comment by leecalcote** [comment]
@Swapnil-Bhabal don't forget to add your star to each repo as you go! 🙂

**Comment by Swapnil-Bhabal** [comment]
Sure @leecalcote
