### ISSUE TITLE
[CI] component build failure

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-linkerd#272]
#### Current Behavior
please see https://github.com/meshery/meshery-linkerd/runs/4565470473?check_suite_focus=true

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Aisuko** [comment]
@DelusionalOptimist Please help us confirm. Is there any API change of Github or Linkerd2 project?
