### ISSUE TITLE
[CI] Define end-to-end integration test assertions 

### ISSUE THREAD

**Issue by warunicorn19** [meshery/meshery-linkerd#284]
#### Current Behavior
The following end-to-end integration test workflow has an incomplete definition of test assertions -

https://github.com/meshery/meshery-linkerd/blob/master/.github/workflows/e2etests.yaml#L110-L112

#### Desired Behavior
Define end-to-end integration test assertions

#### Acceptance Tests
Passing/failing results should show in Meshery Docs compatibility matrix - https://docs.meshery.io/project/compatibility-matrix (this portion of the workflow is complete already).

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Revolyssup** [comment]
@warunicorn19  what do you mean by "incomplete definition of test assertions"

**Comment by leecalcote** [comment]
@Revolyssup this means that of the smi conformance tests that are defined, they do not cover the four smi api specs' functionality completely. More test assertions need to be defined.

**Comment by leecalcote** [comment]
How’s this coming along?

**Comment by Zanda256** [comment]
Some progress, about to open a pr.
