### ISSUE TITLE
Invalid component `Server` schema 

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-linkerd#292]
#### Current Behavior
```
Unsupported field schema for field Server_port: Unknown field type undefined.
{
  "description": "A port name or number. Must exist in a pod spec.",
  "x-kubernetes-int-or-string": true
}
```

#### Screenshots/Logs
<img width="2560" alt="Screen Shot 2022-01-17 at 11 24 35 AM" src="https://user-images.githubusercontent.com/7570704/149814424-760e23dc-f269-4a3f-b0db-a1d2519a8c00.png">

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Revolyssup** [comment]
@leecalcote  RJSF expects each field to have a "type". 
 According to the spec given in kubernetes documentation, if an object has the field "x-kubernetes-int-or-string: true", then it will not have the "type" field. We need to handle this on the UI. Because it does not require backend manipulation as we are just following what the spec is. RJSF should comply with the spec

**Comment by Revolyssup** [comment]
@leecalcote  I just realized this cant be handled on UI, as we directly pass the schema onto library.

**Comment by leecalcote** [comment]
Whether the UI can handle it or not, this is something to be addressed during component generation.

**Comment by Revolyssup** [comment]
> Whether the UI can handle it or not, this is something to be addressed during component generation.

As of now, we don't manipulate the schema internally at backend. The issue is slight incompatibility between kunernetes spec and RJSF. Directly using RJSF instead of adding a thin abstraction on frontend is biting us back. I will see what can be done

**Comment by leecalcote** [comment]
@Revolyssup, did you get this figured out?

**Comment by leecalcote** [comment]
Are we still in the same boat?

**Comment by Revolyssup** [comment]
> Are we still in the same boat?

I think @Abhishek-kumar09  had handled this. Can you confirm @Abhishek-kumar09 ?

**Comment by Abhishek-kumar09** [comment]
Yeah x-kubernetes-int-or-string field is handled and shown as normal text fields in the UI

**Comment by Abhishek-kumar09** [comment]
This issue can be closed.
