### ISSUE TITLE
Failing component creation

### ISSUE THREAD

**Issue by Revolyssup** [meshery/meshery-linkerd#293]
#### Current Behavior

Currently due to helm templates in the yaml (metadata.labels)passed for component creation, component creation fails from kubeopenapi-jsonschema as templates are not resolved and yaml is marked invalid.
#### Expected Behavior

As we do not need labels anyways, we can remove that in meshkit.
#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v
- **Meshery Adapter Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Is this issue only affecting the Meshery Adapter for Linkerd?

**Comment by leecalcote** [comment]
@Revolyssup will you have a look at this one again?
