### ISSUE TITLE
Add end-to-end tests wtih sample apps using service-mesh-pattern file.

### ISSUE THREAD

**Issue by Zanda256** [meshery/meshery-linkerd#320]
#### Current Behavior
Currently e2e tests in the adapter only run tests for vanilla service mesh installation and for addons.

#### Desired Behavior
The link below is of an example patternfile that should also be deployed and assertions should be made.
https://github.com/service-mesh-patterns/service-mesh-patterns/blob/master/samples/minimalistiobookinfo.yaml

#### Mockups

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
uh-oh, the stale bot visited

**Comment by gunishmatta** [comment]
I would love to take this up

**Comment by Zanda256** [comment]
@gunishmatta are you still up for this?

**Comment by Rohith-Raju** [comment]
@leecalcote I'll take this up. Just beware of the silly questions that I ask hereby :smiley:

**Comment by leecalcote** [comment]
@Revolyssup has this not been completed?
