### ISSUE TITLE
[CI] update go version in ci.yml

### ISSUE THREAD

**Issue by cpepper96** [meshery/meshery-linkerd#341]
#### Current Behavior
All meshery adapters use go version 1.17 now, the ci.yml file needs to be updated to reflect this.
#### Desired Behavior
Update the go version to 1.17 in the ci.yml file.
#### Implementation
You can find the outdated version [here](https://github.com/meshery/meshery-linkerd/blob/3ce9d32dfb2f757a7c6ea7297a2b8e599aef4a71/.github/workflows/ci.yml#L38), update to 1.17.
#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Akshit42-hue** [comment]
Can I work on it @cpepper96
