### ISSUE TITLE
[CI] Update the Component generator workflow.

### ISSUE THREAD

**Issue by karnatisrinivas** [meshery/meshery-linkerd#346]
#### Current Behavior

The Components generator file https://github.com/meshery/meshery-linkerd/blob/master/.github/workflows/update-oam-defs.yml using bash which isn't in uniformity with Other adapters.

#### Desired Behavior

Edit the workflow to maintain uniformity with other adapters

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by karnatisrinivas** [comment]
++ @Revolyssup,

**Comment by leecalcote** [comment]
Excellent, @karnatisrinivas
