### ISSUE TITLE
[CI] Components to Docs Workflow failure

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-linkerd#381]
#### Current Behavior
Missing filepath: https://github.com/meshery/meshery-linkerd/runs/7660398762?check_suite_focus=true#step:5:31

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by asubedy** [comment]
Fixed on the Meshery repo .
Meshery/meshery#5965

**Comment by Aisuko** [comment]
So, we can close this issue.
