### ISSUE TITLE
Missing components for few versions of linkerd

### ISSUE THREAD

**Issue by akhilsahuji** [meshery/meshery-linkerd#391]
#### Current Behavior

For some versions, Linkerd has only "Linkerd mesh" and "Configure Addon".Other components are missing as shown in the screenshot.
![less components](https://user-images.githubusercontent.com/46328560/186739198-e93f9d97-bcb5-4740-9d80-3a3cf5b6f945.png)
 missing 

#### Expected Behavior
All the components should appear in all versions as shown in this screenshot.
![linkerd components are missing](https://user-images.githubusercontent.com/46328560/186739554-40e88cc8-44e5-4906-9c18-a33e665dd65a.png)

#### Environment

- **Host OS:** Mac
---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thank you, @akhilsahuji. Is this an issue that you would like to work on?
