### ISSUE TITLE
[CI] Makefile: Golang build command returning warning in golang 1.19

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-linkerd#411]
#### Current Behavior
Contributors execute `make run` to build the adapter. After upgrading from 1.17.8 to 1.19.1, this warning is now shown:

```
# command-line-arguments
ld: warning: -no_pie is deprecated when targeting new OS versions
```

#### Desired Behavior
No build / compiler warnings.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by acald-creator** [comment]
@leecalcote I started getting that warning on my Mac, but not on my Windows/Ubuntu

**Comment by ksankeerth** [comment]
It seems to be a known issue of Golang 1.19.1. https://github.com/golang/go/issues/54482#issuecomment-1251124908

**Comment by acald-creator** [comment]
issue has been resolved from `golang/go` repo, closing this issue
