### ISSUE TITLE
[CI] Update Multi Platform build and Release workflow

### ISSUE THREAD

**Issue by theBeginner86** [meshery/meshery-linkerd#412]
#### Current Behavior

Currently, the [multiplatform.yml](https://github.com/meshery/meshery-linkerd/blob/master/.github/workflows/multi-platform.yml) file is sending unwanted build arguments to docker build process because of which release tag and commit_sha are not being passed over to the image and hence the version of meshery adapter are not visible on-hovering adapters chips on Meshery UI Dashboard.

#### Desired Behavior

This would be fixed when correct build args are passed to the docker build step inside multiplatform workfow.
Required Args:
- VERSION
- GIT_COMMITSHA

Check this commit for reference:
https://github.com/meshery/meshery-consul/commit/446ad170c938c9bfe22e6e8710459d63395b9148

related to: https://github.com/meshery/meshery/issues/6245

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by acald-creator** [comment]
This has been completed by the previous PR on Go 1.19 upgrade. I did not see this open issue until after the fact, but I believe other adapters repo are not completed yet.

**Comment by theBeginner86** [comment]
@XDRAGON2002 you may please check out other open `good first issues` around Layer5 projects.
This link would be helpful: https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Aservice-mesh-performance+user%3Alayer5io+user%3Ameshery

**Comment by XDRAGON2002** [comment]
Sure, no problem!

**Comment by theBeginner86** [comment]
closing this issue as the problem with workflow is already solved by a previous PR https://github.com/meshery/meshery-linkerd/pull/406
