### ISSUE TITLE
Meshery Logo in Dark mode should be white & broken build status image/SVG

### ISSUE THREAD

**Issue by UtkarshMishra12** [meshery/meshery-linkerd#431]
#### Current Behavior

1. Meshery Logo in Dark mode should be white 
2. broken build status image/SVG
3. Slack & Community Link

#### Screenshots/Logs

![image](https://user-images.githubusercontent.com/67385503/203626959-9f5e7fef-acb7-4bfb-b4ca-314b65996147.png)

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v
- **Meshery Adapter Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
2. ```<a href="https://github.com/meshery/meshery-linkerd/actions" alt="Build Status">
  <img src="https://img.shields.io/github/workflow/status/meshery/meshery-linkerd/Release Meshery Linkerd Adapter" /></a>```
