### ISSUE TITLE
Failed to install Linkerd via meshery UI

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-linkerd#447]
_Reported by Chen Lin_:

#### Current Behavior
I used  `mesheryctl` to install Meshery on k8s successfully and then failed to install Linkerd  via meshery UI (istio can be installed)

```
curl -L https://meshery.io/install | PLATFORM=kubernetes bash -
```

#### Expected Behavior
Should be able to install Linkerd  via Meshery UI

#### Screenshots/Logs
the error message from log is linkerd-adaptor

```
time="2022-12-13T01:16:04Z" level=info msg="network-authentication.yaml registered" app=linkerd-adapter
time="2022-12-13T01:16:04Z" level=info msg="Component creation completed for version stable-2.12.3" app=linkerd-adapter
time="2022-12-13T01:16:04Z" level=info msg="Registering workloads with Meshery Server for version stable-2.12.3" app=linkerd-adapter
time="2022-12-13T01:16:04Z" level=info msg="Latest workload components successfully registered for version stable-2.12.3" app=linkerd-adapter
time="2022-12-13T01:18:24Z" level=info msg="Listing Operations" app=linkerd-adapter
time="2022-12-13T01:19:38Z" level=info msg="Listing Operations" app=linkerd-adapter
time="2022-12-13T01:20:21Z" level=info msg="Applying operation linkerd" app=linkerd-adapter
time="2022-12-13T01:20:21Z" level=info msg="Requested install of version: edge-22.4.1" app=linkerd-adapter
time="2022-12-13T01:20:21Z" level=info msg="Requested action is delete: false" app=linkerd-adapter
time="2022-12-13T01:20:21Z" level=info msg="Requested action is in namespace: linkerd-system" app=linkerd-adapter
time="2022-12-13T01:20:22Z" level=error msg="chart \"linkerd2\" version \"22.4.1\" not found in https://helm.linkerd.io/edge repository" app=linkerd-adapter code=1003 probable-cause= severity=2 short-description="Error with Linkerd operation: " suggested-remediation=
time="2022-12-13T01:20:22Z" level=info msg="Attempting manifest installation..." app=linkerd-adapter
time="2022-12-13T01:20:22Z" level=info msg="Looking for linkerd in the path..." app=linkerd-adapter
time="2022-12-13T01:20:22Z" level=info msg="Looking for linkerd in/root/.meshery/bin..." app=linkerd-adapter
time="2022-12-13T01:20:22Z" level=info msg="linkerd not found in the path, downloading..." app=linkerd-adapter
time="2022-12-13T01:20:22Z" level=info msg=Installing... app=linkerd-adapter
time="2022-12-13T01:20:23Z" level=info msg=Done app=linkerd-adapter
time="2022-12-13T01:20:23Z" level=error msg="exit status 2" app=linkerd-adapter code=1003 probable-cause= severity=2 short-description="Error with Linkerd operation: " suggested-remediation=
time="2022-12-13T01:20:23Z" level=error msg="exit status 2" app=linkerd-adapter code=1003 probable-cause= severity=2 short-description="Error with Linkerd operation: " suggested-remediation=
time="2022-12-13T01:20:23Z" level=info msg="Event stored and sent successfully" app=linkerd-adapter
```

#### Environment
- **Platform:** Kubernetes
- **Meshery Server Version:** stable-v0.6.34
- **Meshery Client Version:** stable-v0.6.34
- **Meshery Adapter Version:** stable-[v0.6.3](https://github.com/meshery/meshery-linkerd/releases/tag/v0.6.3)

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Revolyssup this not good. We have an urgent priority issue being visited by the stalebot.

**Comment by Revolyssup** [comment]
This was a versioning issue and was fixed.
