### ISSUE TITLE
 CI: The CI needs to be more simple and more clearly

### ISSUE THREAD

**Issue by Aisuko** [meshery/meshery-linkerd#491]
#### Current Behavior

1. The CI process is triggered by every PR and most time it failed. 
2. All the CIs are triggered by the new PR.
3. The test adapter CIs are failed all time.

#### Desired Behavior

1. We should let the CI simpler it is only responsible to check the code quality.
2. We should make sure the specific CI is triggered by different PR(golang->golang, yaml->yaml)
3. The test adapter CIs should be useful. If it were not useful, we can remove it. we do not want to waste the resources.
<img width="696" alt="image" src="https://github.com/meshery/meshery-linkerd/assets/8053949/97a6ee6e-b015-425f-ad61-3ceb5a30ed86">

#### Acceptance Tests

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by duckling69** [comment]
Hey @Aisuko @leecalcote i'd like to work on this issue

**Comment by Aisuko** [comment]
@duckling69 Thank you.
