### ISSUE TITLE
[Code quality] We need to make sure all the errors from CI are clear

### ISSUE THREAD

**Issue by Aisuko** [meshery/meshery-linkerd#505]
#### Current Behavior

The CI test cases are always failed for many reasons e.g:  code quality, test cases are init failed ...

#### Expected Behavior

Make sure every test-cases we have are working well and makes sure it is useful.

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v
- **Meshery Adapter Version:** stable-v

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by Aisuko** [comment]
More detail about the `golangci-lint` result  https://github.com/meshery/meshery-linkerd/actions/runs/4868680555/jobs/8682362960

**Comment by ayushthe1** [comment]
@Aisuko I'm working on fixing the lint errors

**Comment by Aisuko** [comment]
Thank you @ayushthe1

**Comment by Aisuko** [comment]
* [PR 506](https://github.com/meshery/meshery-linkerd/issues/506) for the `golangci-lint` and the e2e test cases also need to be checked the status.
