### ISSUE TITLE
[chore] update Go to 1.21, and update relevant pkgs

### ISSUE THREAD

**Issue by saurabh100ni** [meshery/meshery-linkerd#545]
### Desired Behaviour
Need to update `Go` to `1.21` in `go.mod` and in `Dockerfile`, and also `Makefile`

- Minor chore on updating `meshkit` and `meshery-adapter-library`

**Comment by ShatilKhan** [comment]
Hi @saurabh100ni , I've just made a PR, couldn't find `go`  version anywhere in `Makefile`

**Comment by ptdatta** [comment]
Hey @saurabh100ni , Can I work on it?

**Comment by saurabh100ni** [comment]
@Ghat0tkach can you look into it ?

**Comment by vishalrajofficial** [comment]
Hey there! Would it be possible for you to assign this issue to me?
