### ISSUE TITLE
[CI] Linkerd Adapter test failures

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-linkerd#567]
#### Current Behavior
https://github.com/meshery/meshery-linkerd/actions/runs/7533690993/job/20506691597?pr=566

#### Desired Behavior
Each of these should be passing.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by code-sleuth** [comment]
@leecalcote pls assign this issue to me as i've been working on it.

**Comment by leecalcote** [comment]
Sound me good. Thanks, @code-sleuth

**Comment by MU5A** [comment]
@code-sleuth if you need some hands let me know please

**Comment by leecalcote** [comment]
@MU5A, yes, please. There are many adapters and only one PR so far. Please jump in.

// @MUzairS15
