### ISSUE TITLE
Ensure Consistent Use of MeshKit Errors in Meshery-Linkerd.

### ISSUE THREAD

**Issue by singh1203** [meshery/meshery-linkerd#583]
#### Current Behavior

Currently, there are instances where errors are being used directly instead of MeshKit errors, which impacts the consistency and quality of error reporting across the project.

#### Desired Behavior

- [ ] Replace all direct usages of errors with MeshKit errors.
- [ ] Ensure that each MeshKit error includes:- Short Description, Long Description, Probable Cause & Suggested Remediation.

#### References

[Meshery Documentation on Meshkit](https://docs.meshery.io/project/contributing/contributing-error)

- Make sure to follow these guidelines during writing Meshkit errors
https://discuss.layer5.io/t/best-practices-for-writing-meshkit-errors/5536

- Also here is an example PR to which you can refer:
[#11340](https://github.com/meshery/meshery/pull/11340)

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by moazfarrukh** [comment]
hi i would like to work on this issue

**Comment by singh1203** [comment]
> hi i would like to work on this issue

Thanks for hopping in @moazfarrukh, here you go.

**Comment by moazfarrukh** [comment]
@singh1203 yes i have started working on it. I have built the project i have been testing each error  by trying to trigger to them to properly understand their behavior before refactoring them, which is taking me a while because there are more than 200 instances of errors in the whole project. i will try to make major progress over this weekend.

**Comment by singh1203** [comment]
> @singh1203 yes i have started working on it. I have built the project i have been testing each error by trying to trigger to them to properly understand their behavior before refactoring them, which is taking me a while because there are more than 200 instances of errors in the whole project. i will try to make major progress over this weekend.

That's excellent! However, I recommend creating a draft PR to represent the progress in the upcoming [meshery dev meeting](https://meshery.io/calendar).
