### ISSUE TITLE
 undefined type types.Capability error on docker build

### ISSUE THREAD

**Issue by moazfarrukh** [meshery/meshery-linkerd#584]
#### Current Behavior
 I seem to be getting this error undefined type types.Capability error when i run docker build . 
command
#### Expected Behavior
there shouldnt be any errors and build should be completed successfully

#### Screenshots/Logs
![image](https://github.com/user-attachments/assets/bdc710b2-e25a-4130-828c-e08446c88448)

#### Environment

- **Host OS:** Linux 
- **Platform:** Docker

**Comment by leecalcote** [comment]
Thank you, @moazfarrukh!

Are you interested in working on this?

**Comment by moazfarrukh** [comment]
@leecalcote i think someone is already working on it at https://github.com/meshery/meshery-adapter-library/pull/161
