### ISSUE TITLE
[CI] Update use of mesheryctl pattern to mesheryctl design

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-linkerd#588]
#### Current Behavior
Workflows are failing to complete successfully due to their use of a deprecated command in Meshery CLI. See https://github.com/meshery/meshery-kuma/actions/runs/12303031125/job/34338314021?pr=443 for an example.

#### Implementation
1. In each applicable workflow, update use of `mesheryctl pattern` to `mesheryctl design`

#### Acceptance Tests
1. Tests are no longer failing in their use of `mesheryctl`.

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by aakankshabhende** [comment]
@leecalcote I want to work on this issue. Could you please assign me this?
