### ISSUE TITLE
[CI] The adapter project's CI should follow Meshery CI use golangci-lint to improve performance

### ISSUE THREAD

**Issue by Aisuko** [meshery/meshery-linkerd#91]
**Enhancement Description**
A brief description of the enhancement.

**Related Challenges**
A brief description of what the problem is. (e.g. I need to be able to...)

---
[Optional] **Alternatives**
A brief description of any alternative solutions or features you've considered.

[Optional] **Additional context**

**Comment by leecalcote** [comment]
@kushthedude are we ready to move to golangci-lint here?

**Comment by leecalcote** [comment]
Thank you, @Aisuko. All of the adapters should follow the same CI workflow. We should be able to copy workflow from any of the other adapters to here. I believe they are all the same now, except for the Linkerd adapter. Is that right, @kushthedude?

**Comment by Aisuko** [comment]
I have been compared the CI with https://github.com/meshery/meshery-kuma/blob/master/.github/workflows/ci.yml project, as you can see both of them are same. So, I believe current CI has no issue and can work well.
